export const EUROPE_COUNTRIES = [
  { code: 'AL', name: 'Shqipëri', flag: '🇦🇱', currency: 'ALL', dialingCode: '+355', isActive: false, localeCode: 'sq' },
  { code: 'AD', name: 'Andorra', flag: '🇦🇩', currency: 'EUR', dialingCode: '+376', isActive: false, localeCode: 'es' },
  { code: 'AT', name: 'Österreich', flag: '🇦🇹', currency: 'EUR', dialingCode: '+43', isActive: false, localeCode: 'de' },
  { code: 'BY', name: 'Беларусь', flag: '🇧🇾', currency: 'BYN', dialingCode: '+375', isActive: false, localeCode: 'ru' },
  { code: 'BE', name: 'België', flag: '🇧🇪', currency: 'EUR', dialingCode: '+32', isActive: false, localeCode: 'nl' },
  { code: 'BA', name: 'Bosna i Hercegovina', flag: '🇧🇦', currency: 'BAM', dialingCode: '+387', isActive: false, localeCode: 'sr' },
  { code: 'BG', name: 'България', flag: '🇧🇬', currency: 'BGN', dialingCode: '+359', isActive: false, localeCode: 'bg' },
  { code: 'HR', name: 'Hrvatska', flag: '🇭🇷', currency: 'EUR', dialingCode: '+385', isActive: false, localeCode: 'hr' },
  { code: 'CY', name: 'Κύπρος', flag: '🇨🇾', currency: 'EUR', dialingCode: '+357', isActive: false, localeCode: 'el' },
  { code: 'CZ', name: 'Česká republika', flag: '🇨🇿', currency: 'CZK', dialingCode: '+420', isActive: false, localeCode: 'cs' },
  { code: 'DK', name: 'Danmark', flag: '🇩🇰', currency: 'DKK', dialingCode: '+45', isActive: false, localeCode: 'da' },
  { code: 'EE', name: 'Eesti', flag: '🇪🇪', currency: 'EUR', dialingCode: '+372', isActive: false, localeCode: 'et' },
  { code: 'FI', name: 'Suomi', flag: '🇫🇮', currency: 'EUR', dialingCode: '+358', isActive: false, localeCode: 'fi' },
  { code: 'FR', name: 'France', flag: '🇫🇷', currency: 'EUR', dialingCode: '+33', isActive: false, localeCode: 'fr' },
  { code: 'DE', name: 'Deutschland', flag: '🇩🇪', currency: 'EUR', dialingCode: '+49', isActive: false, localeCode: 'de' },
  { code: 'GR', name: 'Ελλάδα', flag: '🇬🇷', currency: 'EUR', dialingCode: '+30', isActive: false, localeCode: 'el' },
  { code: 'HU', name: 'Magyarország', flag: '🇭🇺', currency: 'HUF', dialingCode: '+36', isActive: false, localeCode: 'hu' },
  { code: 'IS', name: 'Ísland', flag: '🇮🇸', currency: 'ISK', dialingCode: '+354', isActive: false, localeCode: 'is' },
  { code: 'IE', name: 'Éire', flag: '🇮🇪', currency: 'EUR', dialingCode: '+353', isActive: false, localeCode: 'ga' },
  { code: 'IT', name: 'Italia', flag: '🇮🇹', currency: 'EUR', dialingCode: '+39', isActive: false, localeCode: 'it' },
  { code: 'XK', name: 'Kosova', flag: '🇽🇰', currency: 'EUR', dialingCode: '+383', isActive: false, localeCode: 'sr' },
  { code: 'LV', name: 'Latvija', flag: '🇱🇻', currency: 'EUR', dialingCode: '+371', isActive: false, localeCode: 'lv' },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮', currency: 'CHF', dialingCode: '+423', isActive: false, localeCode: 'de' },
  { code: 'LT', name: 'Lietuva', flag: '🇱🇹', currency: 'EUR', dialingCode: '+370', isActive: false, localeCode: 'lt' },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', currency: 'EUR', dialingCode: '+352', isActive: false, localeCode: 'lb' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹', currency: 'EUR', dialingCode: '+356', isActive: false, localeCode: 'mt' },
  { code: 'MD', name: 'Moldova', flag: '🇲🇩', currency: 'MDL', dialingCode: '+373', isActive: false, localeCode: 'ru' },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨', currency: 'EUR', dialingCode: '+377', isActive: false, localeCode: 'fr' },
  { code: 'ME', name: 'Crna Gora', flag: '🇲🇪', currency: 'EUR', dialingCode: '+382', isActive: false, localeCode: 'sr' },
  { code: 'NL', name: 'Nederland', flag: '🇳🇱', currency: 'EUR', dialingCode: '+31', isActive: false, localeCode: 'nl' },
  { code: 'NO', name: 'Norge', flag: '🇳🇴', currency: 'NOK', dialingCode: '+47', isActive: false, localeCode: 'no' },
  { code: 'PL', name: 'Polska', flag: '🇵🇱', currency: 'PLN', dialingCode: '+48', isActive: false, localeCode: 'pl' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', currency: 'EUR', dialingCode: '+351', isActive: false, localeCode: 'pt' },
  { code: 'RO', name: 'România', flag: '🇷🇴', currency: 'RON', dialingCode: '+40', isActive: false, localeCode: 'ro' },
  { code: 'RU', name: 'Россия', flag: '🇷🇺', currency: 'RUB', dialingCode: '+7', isActive: false, localeCode: 'ru' },
  { code: 'SM', name: 'San Marino', flag: '🇸🇲', currency: 'EUR', dialingCode: '+378', isActive: false, localeCode: 'it' },
  { code: 'RS', name: 'Srbija', flag: '🇷🇸', currency: 'RSD', dialingCode: '+381', isActive: true, localeCode: 'sr' },
  { code: 'SK', name: 'Slovensko', flag: '🇸🇰', currency: 'EUR', dialingCode: '+421', isActive: false, localeCode: 'sk' },
  { code: 'SI', name: 'Slovenija', flag: '🇸🇮', currency: 'EUR', dialingCode: '+386', isActive: false, localeCode: 'sl' },
  { code: 'ES', name: 'España', flag: '🇪🇸', currency: 'EUR', dialingCode: '+34', isActive: true, localeCode: 'es' },
  { code: 'SE', name: 'Sverige', flag: '🇸🇪', currency: 'SEK', dialingCode: '+46', isActive: false, localeCode: 'sv' },
  { code: 'CH', name: 'Schweiz', flag: '🇨🇭', currency: 'CHF', dialingCode: '+41', isActive: false, localeCode: 'de' },
  { code: 'UA', name: 'Україна', flag: '🇺🇦', currency: 'UAH', dialingCode: '+380', isActive: false, localeCode: 'ru' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', currency: 'GBP', dialingCode: '+44', isActive: true, localeCode: 'en' },
  { code: 'VA', name: 'Città del Vaticano', flag: '🇻🇦', currency: 'EUR', dialingCode: '+39', isActive: false, localeCode: 'it' },
]