import { Layout, FileText, Image as ImageIcon, Star, Phone, Clock, Instagram, Sparkles, Calendar, BookOpen, Video, MousePointer, Users, MapPin, Type, Gift, Wine } from 'lucide-react'
import { UtensilsCrossed } from 'lucide-react'

export const BLOCK_TYPES = [
  { type: 'hero', label: 'Hero Banner', icon: Layout, description: 'Large banner with image and text' },
  { type: 'about', label: 'About Section', icon: FileText, description: 'Tell your story' },
  { type: 'gallery', label: 'Image Gallery', icon: ImageIcon, description: 'Showcase photos' },
  { type: 'menu_preview', label: 'Menu Preview', icon: UtensilsCrossed, description: 'Featured menu items' },
  { type: 'testimonials', label: 'Testimonials', icon: Star, description: 'Customer reviews' },
  { type: 'contact', label: 'Contact Info', icon: Phone, description: 'Address and contact details' },
  { type: 'hours', label: 'Opening Hours', icon: Clock, description: 'Business hours' },
  { type: 'social', label: 'Social Links', icon: Instagram, description: 'Social media links' },
  { type: 'specials', label: 'Daily Specials', icon: Sparkles, description: 'Featured dishes & offers' },
  { type: 'events', label: 'Events', icon: Calendar, description: 'Upcoming events & happenings' },
  { type: 'reservation', label: 'Reservations', icon: BookOpen, description: 'Table booking call-to-action' },
  { type: 'features', label: 'Features', icon: Gift, description: 'Amenities & services grid' },
  { type: 'video', label: 'Video', icon: Video, description: 'Embed YouTube or Vimeo' },
  { type: 'cta', label: 'Call to Action', icon: MousePointer, description: 'Promotional banner' },
  { type: 'team', label: 'Team', icon: Users, description: 'Meet the staff/chef' },
  { type: 'text', label: 'Text Block', icon: Type, description: 'Simple text section' },
  { type: 'location', label: 'Location Map', icon: MapPin, description: 'Embedded map' },
  { type: 'drinks', label: 'Drinks Menu', icon: Wine, description: 'Cocktails & beverages' },
]

export const FONT_OPTIONS = [
  { value: 'Inter', label: 'Inter (Modern)' },
  { value: 'Playfair Display', label: 'Playfair Display (Elegant)' },
  { value: 'Poppins', label: 'Poppins (Clean)' },
  { value: 'Roboto', label: 'Roboto (Classic)' },
  { value: 'Lora', label: 'Lora (Serif)' },
  { value: 'Montserrat', label: 'Montserrat (Bold)' },
]

export const THEME_PRESETS = [
  // Dark Themes
  { 
    name: 'Midnight Blue', 
    primary: '#3B82F6', 
    secondary: '#1E293B', 
    background: '#0F172A', 
    foreground: '#F8FAFC',
    accent: '#22D3EE',
    isDark: true,
  },
  { 
    name: 'Obsidian', 
    primary: '#A855F7', 
    secondary: '#1C1917', 
    background: '#0C0A09', 
    foreground: '#FAFAF9',
    accent: '#F472B6',
    isDark: true,
  },
  { 
    name: 'Cyber Noir', 
    primary: '#10B981', 
    secondary: '#18181B', 
    background: '#09090B', 
    foreground: '#FAFAFA',
    accent: '#14B8A6',
    isDark: true,
  },
  { 
    name: 'Deep Ocean', 
    primary: '#06B6D4', 
    secondary: '#164E63', 
    background: '#0E1726', 
    foreground: '#E0F2FE',
    accent: '#38BDF8',
    isDark: true,
  },
  { 
    name: 'Crimson Night', 
    primary: '#EF4444', 
    secondary: '#1F1315', 
    background: '#0D0809', 
    foreground: '#FEF2F2',
    accent: '#FB923C',
    isDark: true,
  },
  { 
    name: 'Forest Dark', 
    primary: '#22C55E', 
    secondary: '#14241A', 
    background: '#0A120E', 
    foreground: '#F0FDF4',
    accent: '#86EFAC',
    isDark: true,
  },
  // Light Themes
  { 
    name: 'Clean White', 
    primary: '#18181B', 
    secondary: '#F4F4F5', 
    background: '#FFFFFF', 
    foreground: '#18181B',
    accent: '#F97316',
    isDark: false,
  },
  { 
    name: 'Soft Cream', 
    primary: '#B45309', 
    secondary: '#FEF3C7', 
    background: '#FFFBEB', 
    foreground: '#78350F',
    accent: '#F59E0B',
    isDark: false,
  },
  { 
    name: 'Fresh Mint', 
    primary: '#16A34A', 
    secondary: '#DCFCE7', 
    background: '#F0FDF4', 
    foreground: '#14532D',
    accent: '#84CC16',
    isDark: false,
  },
  { 
    name: 'Sky Blue', 
    primary: '#0EA5E9', 
    secondary: '#E0F2FE', 
    background: '#F0F9FF', 
    foreground: '#0C4A6E',
    accent: '#06B6D4',
    isDark: false,
  },
  { 
    name: 'Rose Garden', 
    primary: '#E11D48', 
    secondary: '#FFE4E6', 
    background: '#FFF1F2', 
    foreground: '#881337',
    accent: '#F472B6',
    isDark: false,
  },
  { 
    name: 'Lavender Dreams', 
    primary: '#7C3AED', 
    secondary: '#EDE9FE', 
    background: '#FAF5FF', 
    foreground: '#4C1D95',
    accent: '#A78BFA',
    isDark: false,
  },
  { 
    name: 'Warm Sand', 
    primary: '#92400E', 
    secondary: '#FDE68A', 
    background: '#FFFBEB', 
    foreground: '#451A03',
    accent: '#D97706',
    isDark: false,
  },
  { 
    name: 'Nordic Gray', 
    primary: '#6366F1', 
    secondary: '#E5E7EB', 
    background: '#F9FAFB', 
    foreground: '#1F2937',
    accent: '#8B5CF6',
    isDark: false,
  },
]
